apiVersion: batch/v1
kind: Job
metadata:
  name: imagebuilder-simple
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: makisu-worker
        image: gcr.io/makisu-project/makisu-worker:0.0.2
        imagePullPolicy: IfNotPresent
        args:
        - listen
        - -s
        - /makisu-socket/makisu.sock
        volumeMounts:
        - name: socket
          mountPath: /makisu-socket
        - name: context
          mountPath: /makisu-context
      - name: makisu-manager
        image: gcr.io/makisu-project/makisu-client:0.0.2
        imagePullPolicy: IfNotPresent
        workingDir: /tmp/examples/builds/simple
        command:
        - makisu-client
        - --exit
        - build
        - -t=makisu-project/example-simple:0.0.2
        - .
        volumeMounts:
        - name: socket
          mountPath: /makisu-socket
        - name: context
          mountPath: /makisu-context
      volumes:
      - name: socket
        emptyDir: {}
      - name: context
        emptyDir: {}
