version: 0.1
storage:
    cache:
        blobdescriptor: inmemory
    filesystem:
        rootdirectory: /tmp/registry2
    delete:
        enabled: true
http:
    addr: :5003
delete:
    enabled: true
